services:
  atd-ingestion:
    build: .
    image: docker-hub.appsentinels.ai/atd-ingestion:latest
    container_name: atd-ingestion-service
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - KAFKA_TOPIC=${KAFKA_TOPIC:-oat_bus}  # Override topic via environment
    volumes:
      - ./config:/app/config:ro
      - /home/vinaypatil/infosys:/data:ro  # Mount infosys directory for file access
    network_mode: host  # Use host networking to access existing Kafka
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/proc/1/status') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3