# ATD Ingestion Service Configuration for Docker

# Kafka Configuration
kafka:
  topic: test-atd-topic  # Default topic for Docker testing
  bootstrap_servers:
    - localhost:9092  # Using host networking to access existing Kafka
  group_id: atd_ingestion_test
  auto_offset_reset: earliest  # Read from beginning for testing
  enable_auto_commit: true
  poll_timeout_ms: 20000  # Poll timeout in milliseconds (20 seconds)

# ClickHouse Configuration
clickhouse:
  host: localhost  # Using host networking to access existing ClickHouse
  port: 18123
  database: default
  # Optional: Add credentials if required
  # user: default
  # password: password

# AS-CLI Configuration
as_cli:
  executable: as-cli  # Installed in Docker image
  timeout: 300  # Timeout in seconds for each ingestion
  # Additional arguments to pass to as-cli
  additional_args: []

# Thread Pool Configuration
thread_pool_size: 4  # Number of concurrent threads for processing

# Logging Configuration
log_level: INFO
log_file: null  # Use console logging for Docker

# Table Management
auto_create_tables: true  # Pass --create-table flag to as-cli
table_prefix: atd  # Prefix for tenant tables (e.g., atd_tenant1, atd_tenant2)
default_table: atd_logs  # Default table name when no tenant is specified
batch_size: 10000  # Number of records per batch for ingestion
schema_file: /app/schema.json  # Schema file for table creation

# Service Configuration
service:
  # Retry configuration for failed ingestions
  retry:
    enabled: true
    max_attempts: 3
    backoff_seconds: 5